version: '3'
services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./log:/var/log/odoo
      # Inject the addons as a volume as the addons are just here to test the setup for the next step in the
      # docker pipeline.
      - ./test_addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8071:8071"
    environment:
      - LOG_ODOO=/var/log/odoo
      - SPECIFIC_ODOO_RC=/etc/odoo/odoo_specific.conf
    depends_on:
      - db
    command: odoo
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    expose:
      - 5432
volumes:
  odoo-web-data:
  odoo-db-data:
