version: '3'
services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./log:/var/log/odoo
      # Inject the addons as a volume as the addons are just here to test the setup for the next step in the
      # docker pipeline.
      - ./docker_files/odoo_specific.conf:/etc/odoo/odoo_specific.conf
      - ./docker_files/main:/mnt/extra-addons/main
    ports:
      - "8069:8069"
      - "8071:8071"
    environment:
      - LOG_ODOO=/var/log/odoo
      - SPECIFIC_ODOO_RC=/etc/odoo/odoo_specific.conf
    depends_on:
      - db
    command: odoo
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    expose:
      - 5432
  gitoo:
    image: quay.io/numigi/gitoo:1.6
    volumes:
      - .odoo-source-code:/mnt/odoo
      - .extra-addons:/mnt/extra-addons
      - ./gitoo.yml:/gitoo.yml
      - ./gitoo-addons.yml:/gitoo-addons.yml
      - ./patches:/patches
volumes:
  odoo-web-data:
  odoo-db-data:
