version: 2

quay_io_login: &quay_io_login
  name: Login to Quay.io register
  command: docker login quay.io -u "${QUAY_USER}" -p "${QUAY_TOKEN}"

gitoo_install_odoo: &gitoo_install_odoo
  name: Gitoo install odoo source code
  command: ./gitoo-install-odoo.sh
  no_output_timeout: 20m

gitoo_install_extra_addons: &gitoo_install_extra_addons
  name: Gitoo install extra addons
  command: ./gitoo-install-addons.sh

deploy_docker_build: &deploy_docker_build
  name: Docker build
  command: docker build --build-arg GIT_TOKEN=${GIT_TOKEN}  --rm --pull -t "${DOCKER_IMAGE_NAME}" .

deploy_docker_push: &deploy_docker_push
  name: Docker push
  command: docker push "${DOCKER_IMAGE_NAME}"

jobs:
  run-test:
    machine: true
    steps:
       - checkout
       - run:
          name: Setup Log Folder For Reports
          command: sudo mkdir -p ./log && sudo chmod 777 ./log && sudo chmod 777 ./root/__manifest__.py
       - run:
          <<: *gitoo_install_odoo
       - run:
          <<: *gitoo_install_extra_addons
       - run:
          name: Build -- Init Database
          command: docker-compose run --rm odoo odoo --stop-after-init -i main
       - run:
          name: Run our tests
          command: docker-compose run --rm odoo run_pytest.sh

  deploy:
    machine: true
    steps:
       - checkout
       - run:
          <<: *quay_io_login
       - run:
          <<: *gitoo_install_odoo
       - run:
          <<: *gitoo_install_extra_addons
       - run:
          name: Set DOCKER_IMAGE_NAME env variable to odoo-public
          command: |
            echo 'export DOCKER_IMAGE_NAME="quay.io/${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_TAG}"' >> $BASH_ENV
            source $BASH_ENV
            echo docker image name: ${DOCKER_IMAGE_NAME}
       - run:
          <<: *deploy_docker_build
       - run:
          <<: *deploy_docker_push

  deploy-latest:
    machine: true
    steps:
      - checkout
      - run:
          <<: *quay_io_login
      - run:
          <<: *gitoo_install_odoo
      - run:
          <<: *gitoo_install_extra_addons
      - run:
          name: Set DOCKER_IMAGE_NAME env variable to odoo-public
          command: |
            echo 'export DOCKER_IMAGE_NAME="quay.io/${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_BRANCH/\.0/\.latest}"' >> $BASH_ENV
            source $BASH_ENV
            echo docker image name: ${DOCKER_IMAGE_NAME}
      - run:
          <<: *deploy_docker_build
      - run:
          <<: *deploy_docker_push

  auto-tag:
    machine: true
    steps:
      - checkout
      - run:
          <<: *quay_io_login
      - run:
          name: Get nws
          command: |
            curl -L $NWS_BIN_LOCATION > ./nws
            chmod +x ./nws
      - run:
          name: Set tag
          command: |
            ./nws circleci create-tag

  spread-the-version:
    machine: true
    steps:
      - checkout
      - run:
          <<: *quay_io_login
      - run:
          name: Get nws
          command: |
            curl -L $NWS_BIN_LOCATION > ./nws
            chmod +x ./nws
      - run:
          name: Spread the version
          command: |
            ./nws circleci spread

workflows:
  version: 2
  build:
    jobs:
      - run-test:
          filters:
            tags:
              only: /.*/

      - auto-tag:
          context: nws
          requires:
            - run-test
          filters:
            branches:
              only: /^1\d\.0/

      - deploy:
          context: quay.io
          requires:
            - run-test
          filters:
            # Only tags because the env var CIRCLE_TAG is used to define the name of the image.
            tags:
              only: /.*/
            branches:
              ignore: /.*/

      - deploy-latest:
          context: quay.io
          requires:
            - run-test
          filters:
            branches:
              only: /^1\d\.0/

      - spread-the-version:
          context: nws
          requires:
            - deploy
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
