version: 2

quay_io_login: &quay_io_login
  name: Login to Quay.io register
  command: docker login quay.io -u "${QUAY_USER}" -p "${QUAY_TOKEN}"

deploy_docker_build_community: &deploy_docker_build_community
  name: Docker build
  command: docker build --build-arg GIT_TOKEN=${GIT_TOKEN}  --rm --pull -t "${DOCKER_IMAGE_NAME}" .

deploy_docker_push: &deploy_docker_push
  name: Docker push
  command: docker push "${DOCKER_IMAGE_NAME}"

jobs:
  run-test:
    machine: true
    steps:
       - checkout

       - run:
          name: Setup Log Folder For Reports
          command: sudo mkdir -p ./log && sudo chmod 777 ./log

       - run:
          name: Build -- Init Database
          command: docker-compose run --rm odoo odoo --stop-after-init -i main


       - run:
          name: Run our tests
          command: docker-compose run --rm odoo run_pytest.sh

       - run:
          name: Run Tests
          command: docker-compose run --rm odoo run_test.sh

       - run:
          name: Codacy Coverage
          command: |
            pip install codacy-coverage==1.3.10
            python-codacy-coverage -r ./log/coverage.xml

       - store_test_results:
          path: ./log

  deploy-latest:
    machine: true
    steps:
      - checkout
      - run:
          <<: *quay_io_login
      - run:
          name: Set DOCKER_IMAGE_NAME env variable to odoo-base-community
          command: |
            echo 'export DOCKER_IMAGE_NAME="quay.io/${CIRCLE_PROJECT_USERNAME,,}/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_BRANCH/\.0/\.latest}"' >> $BASH_ENV
            source $BASH_ENV
            echo docker image name: ${DOCKER_IMAGE_NAME}
      - run:
          <<: *deploy_docker_build_community
      - run:
          <<: *deploy_docker_push

workflows:
  version: 2
  build:
    jobs:
      - run-test:
          filters:
            tags:
              only: /.*/

      # build latest tags for the 1?.0 branches so it represents the "master" branch
      - deploy-latest:
          context: quay.io
          requires:
            - run-test
          filters:
            branches:
              only: /^1\d\.0/

